-- Dalil D1 schema V1
-- IDs are generated by the application. Timestamps are UTC ISO-8601 strings.
-- D1 enforces foreign keys by default.

CREATE TABLE sources (
  id TEXT PRIMARY KEY NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('github', 'rss', 'api', 'website', 'paper_index', 'model_hub', 'other')),
  name TEXT NOT NULL CHECK (length(name) BETWEEN 1 AND 160),
  base_url TEXT NOT NULL CHECK (base_url LIKE 'https://%'),
  enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
) STRICT;

CREATE TABLE ingestion_runs (
  id TEXT PRIMARY KEY NOT NULL,
  source_id TEXT NOT NULL,
  run_kind TEXT NOT NULL CHECK (run_kind IN ('scheduled', 'manual', 'backfill')),
  status TEXT NOT NULL CHECK (status IN ('running', 'succeeded', 'partial', 'failed')),
  started_at TEXT NOT NULL,
  finished_at TEXT,
  items_seen INTEGER NOT NULL DEFAULT 0 CHECK (items_seen >= 0),
  items_written INTEGER NOT NULL DEFAULT 0 CHECK (items_written >= 0),
  items_failed INTEGER NOT NULL DEFAULT 0 CHECK (items_failed >= 0),
  error_code TEXT,
  FOREIGN KEY (source_id) REFERENCES sources(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) STRICT;

CREATE INDEX idx_ingestion_runs_source_started
  ON ingestion_runs(source_id, started_at DESC);

CREATE TABLE content_items (
  id TEXT PRIMARY KEY NOT NULL,
  source_id TEXT NOT NULL,
  external_id TEXT NOT NULL CHECK (length(external_id) BETWEEN 1 AND 512),
  kind TEXT NOT NULL CHECK (kind IN ('repository', 'article', 'paper', 'model', 'release', 'advisory', 'other')),
  canonical_url TEXT NOT NULL CHECK (canonical_url LIKE 'https://%'),
  title TEXT NOT NULL CHECK (length(title) BETWEEN 1 AND 500),
  summary TEXT,
  published_at TEXT,
  source_updated_at TEXT,
  first_seen_at TEXT NOT NULL,
  last_seen_at TEXT NOT NULL,
  content_hash TEXT NOT NULL CHECK (length(content_hash) BETWEEN 16 AND 128),
  state TEXT NOT NULL DEFAULT 'live' CHECK (state IN ('live', 'removed', 'unavailable')),
  FOREIGN KEY (source_id) REFERENCES sources(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  UNIQUE (source_id, external_id)
) STRICT;

CREATE INDEX idx_content_items_kind_last_seen
  ON content_items(kind, last_seen_at DESC);

CREATE INDEX idx_content_items_source_last_seen
  ON content_items(source_id, last_seen_at DESC);

CREATE TABLE repository_snapshots (
  item_id TEXT NOT NULL,
  observed_at TEXT NOT NULL,
  stars INTEGER NOT NULL CHECK (stars >= 0),
  forks INTEGER NOT NULL CHECK (forks >= 0),
  open_issues_and_pull_requests INTEGER NOT NULL CHECK (open_issues_and_pull_requests >= 0),
  contributor_count INTEGER CHECK (contributor_count IS NULL OR contributor_count >= 0),
  language TEXT,
  source_updated_at TEXT,
  PRIMARY KEY (item_id, observed_at),
  FOREIGN KEY (item_id) REFERENCES content_items(id) ON UPDATE RESTRICT ON DELETE CASCADE
) STRICT;

CREATE INDEX idx_repository_snapshots_observed
  ON repository_snapshots(observed_at DESC);

CREATE TABLE stories (
  id TEXT PRIMARY KEY NOT NULL,
  title TEXT NOT NULL CHECK (length(title) BETWEEN 1 AND 500),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived')),
  first_seen_at TEXT NOT NULL,
  last_seen_at TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
) STRICT;

CREATE INDEX idx_stories_status_last_seen
  ON stories(status, last_seen_at DESC);

CREATE TABLE story_items (
  story_id TEXT NOT NULL,
  item_id TEXT NOT NULL,
  match_kind TEXT NOT NULL CHECK (match_kind IN ('exact', 'canonical', 'heuristic', 'semantic', 'manual')),
  confidence_basis_points INTEGER CHECK (
    confidence_basis_points IS NULL OR
    (confidence_basis_points BETWEEN 0 AND 10000)
  ),
  created_at TEXT NOT NULL,
  PRIMARY KEY (story_id, item_id),
  FOREIGN KEY (story_id) REFERENCES stories(id) ON UPDATE RESTRICT ON DELETE CASCADE,
  FOREIGN KEY (item_id) REFERENCES content_items(id) ON UPDATE RESTRICT ON DELETE CASCADE
) STRICT;

CREATE INDEX idx_story_items_item
  ON story_items(item_id);

CREATE TABLE claims (
  id TEXT PRIMARY KEY NOT NULL,
  item_id TEXT NOT NULL,
  statement TEXT NOT NULL CHECK (length(statement) BETWEEN 1 AND 2000),
  claim_hash TEXT NOT NULL CHECK (length(claim_hash) BETWEEN 16 AND 128),
  extraction_method TEXT NOT NULL CHECK (extraction_method IN ('deterministic', 'model', 'manual')),
  extracted_at TEXT NOT NULL,
  FOREIGN KEY (item_id) REFERENCES content_items(id) ON UPDATE RESTRICT ON DELETE CASCADE,
  UNIQUE (item_id, claim_hash)
) STRICT;

CREATE INDEX idx_claims_item
  ON claims(item_id);

CREATE TABLE evidence_records (
  id TEXT PRIMARY KEY NOT NULL,
  source_id TEXT NOT NULL,
  item_id TEXT,
  canonical_url TEXT NOT NULL CHECK (canonical_url LIKE 'https://%'),
  title TEXT CHECK (title IS NULL OR length(title) <= 500),
  evidence_kind TEXT NOT NULL CHECK (evidence_kind IN ('primary', 'independent', 'official', 'data', 'code', 'paper', 'other')),
  observed_at TEXT NOT NULL,
  content_hash TEXT NOT NULL CHECK (length(content_hash) BETWEEN 16 AND 128),
  object_key TEXT,
  FOREIGN KEY (source_id) REFERENCES sources(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (item_id) REFERENCES content_items(id) ON UPDATE RESTRICT ON DELETE SET NULL
) STRICT;

CREATE INDEX idx_evidence_records_source_observed
  ON evidence_records(source_id, observed_at DESC);

CREATE TABLE claim_evidence (
  claim_id TEXT NOT NULL,
  evidence_id TEXT NOT NULL,
  relation TEXT NOT NULL CHECK (relation IN ('supports', 'contradicts', 'context')),
  created_at TEXT NOT NULL,
  PRIMARY KEY (claim_id, evidence_id, relation),
  FOREIGN KEY (claim_id) REFERENCES claims(id) ON UPDATE RESTRICT ON DELETE CASCADE,
  FOREIGN KEY (evidence_id) REFERENCES evidence_records(id) ON UPDATE RESTRICT ON DELETE CASCADE
) STRICT;

CREATE INDEX idx_claim_evidence_evidence
  ON claim_evidence(evidence_id);

CREATE TABLE country_metrics_daily (
  day TEXT NOT NULL CHECK (
    length(day) = 10 AND
    day GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'
  ),
  country_iso2 TEXT NOT NULL CHECK (
    length(country_iso2) = 2 AND
    country_iso2 = upper(country_iso2) AND
    country_iso2 GLOB '[A-Z][A-Z]'
  ),
  requests INTEGER NOT NULL DEFAULT 0 CHECK (requests >= 0),
  pageviews INTEGER NOT NULL DEFAULT 0 CHECK (pageviews >= 0),
  responses_2xx INTEGER NOT NULL DEFAULT 0 CHECK (responses_2xx >= 0),
  responses_3xx INTEGER NOT NULL DEFAULT 0 CHECK (responses_3xx >= 0),
  responses_4xx INTEGER NOT NULL DEFAULT 0 CHECK (responses_4xx >= 0),
  responses_5xx INTEGER NOT NULL DEFAULT 0 CHECK (responses_5xx >= 0),
  latency_sum_ms INTEGER NOT NULL DEFAULT 0 CHECK (latency_sum_ms >= 0),
  latency_samples INTEGER NOT NULL DEFAULT 0 CHECK (latency_samples >= 0),
  PRIMARY KEY (day, country_iso2)
) STRICT;

CREATE INDEX idx_country_metrics_country_day
  ON country_metrics_daily(country_iso2, day DESC);
